### PR TITLE
Implement <virtual-content>

### LINKED ISSUE #113: Implement <virtual-content>
In https://github.com/valdrinkoshi/virtual-scroller/issues/72 we talked about `virtual-scroller` and `virtual-content`. This issue tracks the definition & implementation of `virtual-content`.

`<virtual-content>` auto-sizes itself according to the estimated size of the items (sets its min-width/height), and creates DOM only for the visible portion of it. It computes the portion of the viewport currently visible by listening for scroll events on the scroll parent. It can be contained in any scroll container.

### PR DESCRIPTION
**Pull request by valdrinkoshi**
Fixes #113.
We expose a private property to be able to override the scrollTarget when extending the custom element.

Note that we search for the scroll target on first attached, and that relies on the fact that the parent is already setup to be overflowing. It might be worth exposing a new property for `<virtual-content>` to set the scroll target, but let's wait to see if this is actually needed by collecting requirements and use cases first.

### CODE REVIEW

**Comment by domenic** [comment]
I'll try to add some docs for this. Preferably without renaming the entire repository... ^_^

The scroll-target-finder is a bit tricky, and I wonder if there's any better way to do that, but nothing comes to mind immediately...

**Comment by valdrinkoshi** [comment]
We could also expose it as a property and have its default be the `parentNode`.

**Comment by valdrinkoshi** [comment]
Actually, if we use InteractionObserver #54 we shouldn't need to know who's the scroll target...For that reason I would not expose `scrollTarget` and keep it an implementation detail for now

**Comment by domenic** [comment]
Closing this as this is related to the virtual-scroller prototype implementation and we intend to make this repository focus on the standards side of it. Thanks as always for your trailblazing work @valdrinkoshi! I think we did eventually come around to the point of view that "virtual content" style behavior is the right starting point.

**Pull request closed without merging**
