### PR TITLE
Consistently use .mjs to denote modules

### PR DESCRIPTION
**Pull request by mathiasbynens**
Module scripts behave differently than classic scripts. As such, I'd like to suggest explicitly denoting the difference by using the .mjs extension for modules and .js for classic scripts.

More details on this guidance: https://developers.google.com/web/fundamentals/primers/modules#mjs

Similar changes have landed upstream in the Layered APIs repository. It would be nice to be consistent with that.

### CODE REVIEW

**Comment by domenic** [comment]
Readme line endings changed?

**Comment by mathiasbynens** [comment]
They were CRLF for some reason. The patch makes them LF which is consistent with the other files.

**Comment by domenic** [comment]
Can you separate that out into a separate commit, so that we can see the actual change?

**Comment by mathiasbynens** [comment]
@domenic Done. (I ran `unix2dos README.md` and amended the commit.)

**Comment by domenic** [comment]
Things keep changing in this repository, so I'll need to retarget this against the two new branches (see #155). Let me close this and commit directly to those, with you as the author.

**Pull request closed without merging**
